### ISSUE TITLE
the sra download link do not work

### ISSUE THREAD

**Issue by tianxiahuihui** [ewels/sra-explorer#14]
Hello, I get a Raw SRA Download URLs like this: [`ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByRun/sra/SRR/SRR121/SRR1217720/SRR1217720.sra`](ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByRun/sra/SRR/SRR121/SRR1217720/SRR1217720.sra), but the file does not exist.

I also found the sra data links in the offical urls was [`https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR1217720`](https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR1217720), which is different with your result.

I also hope you can supply an aspera commmand to download the sra file. Can you help me?

Thank you

**Comment by ewels** [comment]
Hi @tianxiahuihui,

The two links are different because the first is an FTP link, the second is a HTTP web link. The FTP link is directly to the file - the HTTP link you gave is for a web page _about_ the file.

FTP is usually better for downloading large files. You are correct that the FTP link is broken though - I get the same when I search for / try the link. I tried one or two others and got the same. It seems that the runs available on FTP currently are very limited: see [`ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByRun/sra/SRR/SRR121/`](ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByRun/sra/SRR/SRR121/)

...ok, after digging around a little I found [this blog post](https://ncbiinsights.ncbi.nlm.nih.gov/2019/10/17/users-of-the-sra-ftp-site-try-the-sra-toolkit/) which says:

> If you download data from the SRA (Sequence Read Archive) FTP site, we would encourage you to try the SRA Toolkit. This is particularly true if you use the SRA Fuse/FTP site at ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant, ***which the SRA team will decommission on December 1, 2019.***

So they're maybe a little early, but basically yes, it sounds like the SRA FTP links will start to fail. I'll need to look into updating sra-explorer as appropriate.

In the short term, you can just download FastQ files for the run from the EBI ENA (see the _FastQ Downloads_ tab). Here you can also copy commands for downloading with aspera.

Thank you for reporting this, and let me know if you run in to any problems with the FastQ downloads.

Phil

**Comment by tianxiahuihui** [comment]
OK.  Thank you.

**Comment by dbell30** [comment]
Hi, is there an alternative way to download via. request. Without their SRA Toolkit? @tianxiahuihui @ewels

**Comment by ewels** [comment]
Most datasets are mirrored from the SRA to the ENA and available as FastQ files directly. This sra-explorer tool provides download links for these FastQ files where available - you can download these files however you like.

I hope that helps!

**Comment by dbell30** [comment]
Hi,

Can you provide me a link to the service for downloading .fastq files directly, please?

Would there be an API to integrate this service you're talking about?

Kind Regards,
Daniel Bell
________________________________

**Comment by ewels** [comment]
@dbell30 I don't really understand - the whole point of this tool is to generate those links for you, that's all it does 🙂 http://sra-explorer.info/

SRA explorer is built using APIs provided by the NCBI SRA and EBI ENA, so yes there is already APIs available for this - from then. It's the ENA that has FastQ file downloads typically. Please see the repository readme for more information and links to those services.

Phil
