### ISSUE TITLE
GEO accession not working

### ISSUE THREAD

**Issue by igordot** [ewels/sra-explorer#20]
There is a similar previous issue (https://github.com/ewels/sra-explorer/issues/16). In my case, the GEO submission is sequencing-based, not microarray.

As in the other issue, it somehow does not exist in SRA based on the GSE accession: https://www.ncbi.nlm.nih.gov/sra/?term=GSE98964
The samples exist based on the SRA accession: https://www.ncbi.nlm.nih.gov/sra/?term=SRA561954
The GEO accession works in ENA: https://www.ebi.ac.uk/ena/data/search?query=GSE98964

Do you know how this may have happened? It would be great if SRA Explorer could somehow account for that.

**Comment by ewels** [comment]
Hi @igordot,

This is down to how the authors submit their data to GEO and the SRA. It's not something that I can account for I'm afraid - I just take the results that the SRA give me.

Searching for `SRA561954` in sra-explorer seems to work fine ✅ 

Phil

**Comment by ewels** [comment]
ps. It is interesting that the GEO accession works in the ENA. It could be nice "one day" to enable primary searches directly in the ENA instead of only going there with the SRA results. This would require a substantial rewrite of the code base though, which sadly I don't have time for in the foreseeable future (or rather, can't prioritise over other projects).

**Comment by igordot** [comment]
Do you know why this happens? Is there some setting or parameter (other than trying the SRA search) that I can look for to determine if certain GEO accessions will work or not? To me, it seems random.

**Comment by ewels** [comment]
In my experience it's also random. I think that it's down to who submits the data and which metadata fields they fill in..
