### ISSUE TITLE
Aspera FastQ file link not appearing

### ISSUE THREAD

**Issue by JonathonMifsud** [ewels/sra-explorer#24]
Hi,

It appears that the Aspera FastQ file links are no longer appearing. I suspect this is not a bug with sra-explorer but thought I should open an issue in case. I've tried a number of accession including ` PRJEB8073` and `ERP009109` with no luck.

Thank you for this wonderful tool, it has been really helpful.

**Comment by harris-2374** [comment]
I am having the same issue when trying to get any of the FastQ file links. I have tried this with accessions SRR5815677 and SRR8377759.

**Comment by ewels** [comment]
I suspect that this is due to #15 and #17 perhaps? Though if it’s ENA it shouldn’t be. Could you try getting the aspera link from the ENA website to compare?

**Comment by JonathonMifsud** [comment]
Using accession SRR1448774 the ENA ftp link is 
`ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR144/004/SRR1448774/SRR1448774.fastq.gz` not sure if this is informative?

I opened an issue https://github.com/wwood/ena-fast-download/issues/6 with another ENA tool I use. I may be totally wrong as I am just a beginner with using the ENA but it looks like the solution to the linked issue was changing the ENA path to the fasta ftp's from something like this:

`https://www.ebi.ac.uk/ena/data/warehouse/filereport?accession={}&result=read_run&fields=fastq_ftp&download=txt`

to this:

`https://www.ebi.ac.uk/ena/portal/api/filereport?accession={}&result=read_run&fields=fastq_ftp`

Cheers,

**Comment by sgmiriuka** [comment]
Just posted it in another thread, looks like ENA change its browser on August 5th. 
@ewels can you check? this tool is just great, don't want to lose it.

**Comment by ewels** [comment]
Hi all,

I will check / fix ASAP. Apologies for the delay, this happened right at the start of my vacation. I'm back now but battling a backlog on all of my tools plus only working 3 days a week. If anyone fancies proposing a fix via a pull-request that would be brilliant.

Otherwise I will try to get to this in a week or two.

Phil

**Comment by vonMeyenn** [comment]
Hi Phil

Have you considered to also makes this fix available for Labrador?

Best wishes 
Ferdinand

**Comment by ewels** [comment]
Ah of course, Labrador too. We'll see - probably not I'm afraid as I consider it a legacy project now (I haven't done any work on Labrador or used it myself in over 4 years now and did the bulk of work on it 7-8 years ago). But depending on how easy the fix is I might look into it, or someone else might be able to. I'll make an issue on that repo for that.

**Comment by ewels** [comment]
Hi all,

The issues with SRA-explorer have been fixed in @agduncan94 in PR #27, so we should be back up and running now. Please let me know if you hit any other problems.

Note that I'm still planning to spruce up the code a little to give better error handling for the future.

Thanks for reporting the issue,

Phil
