### ISSUE TITLE
SRA-explorer not retrieving results

### ISSUE THREAD

**Issue by sivico26** [ewels/sra-explorer#25]
Hi, 

I love using SRA-explorer since I discovered a couple years ago. I tried to use it today but it did not retrieve any result no matter what term did I use (including the sample terms). I tried different browsers (Firefox, Chrome, Opera) but the problem persisted. I use Ubuntu 18.04, if that helps. 

I thought the problem was in my end, but the same happens to a friend in a different machine with Windows 10.

Has someone else reported something similar? Any thoughts on the matter?

**Comment by sgmiriuka** [comment]
Same problem. Almost sure related to the recent major change in EBI home address. I just found that SRA-explorer code looks for 'ebi.ac.uk/ena/browser' but now search is under 'ebi.ac.uk/ena/browser/search', but not sure if ftp is same address. In fact, first address is dead. 
[https://www.ebi.ac.uk/about/news/service-news/retirement-old-ena-browser-5th-august-2020](See EBI news)

**Comment by ewels** [comment]
Hi both,

Yes, apologies - I got a whole bunch of reports around the same time and you're right, this is due to a change in the upstream APIs. I have now at least added a banner saying that it's broken: https://github.com/ewels/sra-explorer/commit/2a3320e0e7953e3ac2e3297d0c48ad638d56a99a

I want to do a fair bit of maintenance work on SRA-Explorer anyway, so will try to find to fix this ASAP. In the mean time, if you think you know a fix then please feel free to submit a pull-request, that would be very helpful!

Phil

**Comment by ewels** [comment]
Hi all,

The issues with SRA-explorer have been fixed in @agduncan94 in PR #27, so we should be back up and running now. Please let me know if you hit any other problems.

Note that I'm still planning to spruce up the code a little to give better error handling for the future.

Thanks for reporting the issue,

Phil
