### ISSUE TITLE
SRA explorer problem

### ISSUE THREAD

**Issue by mospinam1** [ewels/sra-explorer#26]
Hello,

These days I have been using the SRA-explorer, but once I write down the term of interest it doesn't provide a result no matter what type of term I introduce. I have already tried different web browsers, yet, I still don't get a result. Any ideas?

**Comment by ChristopherLeeZG** [comment]
Same problem.

**Comment by ewels** [comment]
Yes there have been several issue reports in the past few days, so I guess something the tool relies on has changed / broken.

I’m on vacation currently, but will look into it when I am back at work in a few weeks.

Thanks for reporting!

Phil

**Comment by ewels** [comment]
Hi all,

The issues with SRA-explorer have been fixed in @agduncan94 in PR #27, so we should be back up and running now. Please let me know if you hit any other problems.

Note that I'm still planning to spruce up the code a little to give better error handling for the future.

Thanks for reporting the issue,

Phil
