### ISSUE TITLE
multiple GSM accessions as input

### ISSUE THREAD

**Issue by FrAoJm** [ewels/sra-explorer#38]
Hi! 

I try to put several GSMxxxx accessions separated by ",", but it returns nothing, not even an error. Is it possible to find a batch of files somehow?
Thanks!

**Comment by ewels** [comment]
If I try it space delimited:

```
GSM758560 GSM758562 GSM758565
```

Then the SRA converts this query to:

```
GSM758560[All Fields] AND GSM758562[All Fields] AND GSM758565[All Fields]
```

which gives 0 results. This makes sense, as it's look for a single result with all 3 identifiers because of the `AND` operators.

If I manually change these to `OR` then I get the expected results:

```
GSM758560[All Fields] OR GSM758562[All Fields] OR GSM758565[All Fields]
```

So, looks like you need to separate with `OR` and it should work 👍🏻 

Hope that helps!

Phil

**Comment by FrAoJm** [comment]
So quick!! it works nicely!! :=)
Thank you!!
