### ISSUE TITLE
Quotes needed for wget command

### ISSUE THREAD

**Issue by ewels** [ewels/sra-explorer#9]
Hi Phil,

I just stumbled across this while trying to solve a different problem. Can you tell me how to get the result which is displayed in the web broswer via the command line?

I have a few hundred accessions (in different bioprojects), and can't figure out how to do this on command line with wget or curl.

Thanks,

Phil

_Originally posted by @flashton2003 in https://github.com/ewels/sra-explorer/issues/3#issuecomment-503859975_

**Comment by ewels** [comment]
Oh, actually, my colleague helped me sort it.

I just needed quotes around the URL being given to wget and then quotes around the weirdly named output file when I `cat` it.

_Originally posted by @flashton2003 in https://github.com/ewels/sra-explorer/issues/3#issuecomment-503869706_

**Comment by ewels** [comment]
Hi @flashton2003 - I moved your comments to a new issue thread, I hope that's ok. Will make it a lot easier for me to keep track of.

Even though you were able to solve the problem, I'd be curious to know which samples caused the problem. It sounds like spaces or strange characters were making the download filename problematic, however SRA explorer _should_ sanitise the filename to prevent this (or so I thought). If you could let me know which samples were the ones causing the problem, then maybe I can fix this for future users.

Thanks,

Phil

**Comment by flashton2003** [comment]
Hi Phil,

Sorry for the slow response. I wasn't using SRA explorer directly, it was more just a question about how does SRA explorer get the fastq ftp addresses from the ENA API. So, a more basic question about wget options really. Sorry, I should have made that clearer.

The reason I wasn't able to use SRA explorer directly is because the data is spread across lots of bioprojects, and as far as I can tell, SRA explorer doesn't support this?

Thanks,

Phil

**Comment by ewels** [comment]
Gotcha 👍 

sra-explorer uses the NCBI SRA search to find accessions, so as long as the data you want appears in the search results there, you should be able to fetch it all..

Phil
